# LISTING 9.9
# CAPITALISES THE FILE PROVIDED BY USER INPUT FILENAME USING CONVERTUPPER.PY
# AUTHOR: RICK HALTERMAN
# LAST MODIFIED:

FROM CONVERTUPPER IMPORT CAPITALIZE

CAPITALIZE(INPUT('PLEASE GIVE FILE NAME TO CONVERT TO UPPER CASE FILE: '))
