#!/usr/bin/env python3

# Example 20-18a
# Imports and uses the C extension module
# Author: Mark Lutz, Paul I Ighofose
# Last modified: 2019-04-26

# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info, path
path.append('../sourceFiles/libraries')
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_number')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_number')
    _number = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_number', [dirname(__file__)])
        except ImportError:
            import _number
            return _number
        try:
            _mod = imp.load_module('_number', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _number = swig_import_helper()
    del swig_import_helper
else:
    import _number
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class Number(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Number, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Number, name)
    __repr__ = _swig_repr

    def __init__(self, start):
        this = _number.new_Number(start)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _number.delete_Number
    __del__ = lambda self: None

    def add(self, value):
        return _number.Number_add(self, value)

    def sub(self, value):
        return _number.Number_sub(self, value)

    def square(self):
        return _number.Number_square(self)

    def display(self):
        return _number.Number_display(self)
    __swig_setmethods__["data"] = _number.Number_data_set
    __swig_getmethods__["data"] = _number.Number_data_get
    if _newclass:
        data = _swig_property(_number.Number_data_get, _number.Number_data_set)
Number_swigregister = _number.Number_swigregister
Number_swigregister(Number)

# This file is compatible with both classic and new-style classes.


